### ISSUE TITLE
ПАРСЕР

### ISSUE THREAD

**Issue by PavelKoshlyakov** [kkrinitskiy/mentoring#18]
Реализовать парсер сайтов.
Под каждый сайт создаётся отдельный класс.

Опрос информации с сайта выполняется каждые 10 секунд, при чём, с нескольких источников параллельно. Полученная информация записывается в соотвествующий файл (для каждого свой).

**Comment by kkrinitskiy** [comment]
https://github.com/kkrinitskiy/parser
